name: Continuous Integration

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
  # enable manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run tests and generate test report
        id: tests
        run: ./gradlew test --info

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/reports/tests/

      - name: Build with Gradle
        if: steps.tests.outcome == 'success'
        run: ./gradlew clean build
